thepwagner/action-update

actions/handlers.go, actions/updateaction/handlers.go
I'm about to make a release, then go click the `workflow_dispatch` button in several downstream dependencies. There's _got_ to be a better way.
By reacting to `repository_dispatch`, I can signal downstream repositories that they should consume the release that was just published. I don't mind maintaining the mapping manually.
=> Repository dispatch

.github/workflows/release.yaml, script/release
Following from #4 , hopefully `v0.0.3` will be the last release that doesn't get magically PR'ed like this.
There's an exciting extension here for evaluating pre-releases... braindumping on that:
* Open an issue on _this_ repository
* Pass the issue URL to consumers
* Have consumers include the issue URL in PR description, causing GitHub to link
That's a cool demo, right?
I don't think we can do better: the checkruns we care about are for the downstream project's CI. Since those are triggered by Actions, it's impossible for an Actions-based hook like `action-update` can offer to capture feedback.
Maybe _this_ action could block, polling downstream checks to evaluate results?
=> send repository_dispatch on release

.golangci.yml, repo/git.go, repo/github.go, updater/mockrepo_test.go, updater/update.go, updater/updater.go, updater/updater_test.go
Finally implementing the vaporware from https://github.com/thepwagner/action-update/pull/2 !
Adds `Repo.ExistingUpdates()` to query the recent update history from the repository by querying for signed PRs. This replaces a v0 path that parsed branch names - full circle.
Teach `RepoUpdater` to apply `updater.Group.CoolDown` when checking each update group, and ignore groups within their cooldown.
This is the dream. Check every night for _most_ dependencies, but https://github.com/aws/aws-sdk-go/tags only appears weekly.
=> Implement cooldowns

actions/env.go, actions/env_test.go, go.mod, go.sum
Adds support for a new input: `ignore`, and the ability to filter paths against it.
This is for places that walk `Dockerfile`s to evaluate updates: `vendor/**` and `**/testdata/**` are usually not worth including.
=> path ignores

go.mod, go.sum
Here is github.com/bmatcuk/doublestar/v2 v2.0.3, I hope it works.
=> Update github.com/bmatcuk/doublestar/v2 from v2.0.1 to v2.0.3

go.mod, go.sum
Here is github.com/bmatcuk/doublestar/v2 v2.0.4, I hope it works.
=> Update github.com/bmatcuk/doublestar/v2 from v2.0.3 to v2.0.4

go.mod, go.sum
Here is golang.org/x/mod v0.4.0, I hope it works.
=> Update golang.org/x/mod from v0.3.0 to v0.4.0

actions/env.go, actions/env_test.go, actions/handlers.go, actions/handlers_test.go, actions/updateaction/issuecomment.go, actions/updateaction/pullrequest.go, actions/updateaction/pullrequest_test.go, actions/updateaction/release.go, actions/updateaction/repositorydispatch.go, go.mod, go.sum, repo/github.go, repo/pullrequest.go
Here is github.com/google/go-github/v32 v33.0.0, I hope it works.
=> Update github.com/google/go-github/v32 from v32.1.0 to v33.0.0

go.mod, go.sum
Here is github.com/otiai10/copy v1.4.0, I hope it works.
=> Update github.com/otiai10/copy from v1.3.0 to v1.4.0

go.mod, go.sum
Here is github.com/otiai10/copy v1.4.1, I hope it works.
=> Update github.com/otiai10/copy from v1.4.0 to v1.4.1

go.mod, go.sum
Here is github.com/otiai10/copy v1.4.2, I hope it works.
=> Update github.com/otiai10/copy from v1.4.1 to v1.4.2

script/tools/golangci-lint/Dockerfile
Here is golangci/golangci-lint v1.35.0-alpine, I hope it works.
=> Update golangci/golangci-lint from v1.31.0-alpine to v1.35.0-alpine

go.mod, go.sum
Here is github.com/stretchr/testify v1.7.0, I hope it works.
=> Update github.com/stretchr/testify from v1.6.1 to v1.7.0

go.mod, go.sum
Here is golang.org/x/mod v0.4.1, I hope it works.
=> Update golang.org/x/mod from v0.4.0 to v0.4.1

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.15.7, I hope it works.
=> Update golang from 1.15.6 to 1.15.7

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.15.8, I hope it works.
=> Update golang from 1.15.7 to 1.15.8

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.0, I hope it works.
=> Update golang from 1.15.8 to 1.16.0

go.mod, go.sum
Here is github.com/otiai10/copy v1.5.0, I hope it works.
=> Update github.com/otiai10/copy from v1.4.2 to v1.5.0

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.1, I hope it works.
=> Update golang from 1.16.0 to 1.16.1

go.mod, go.sum
Here is golang.org/x/mod v0.4.2, I hope it works.
=> Update golang.org/x/mod from v0.4.1 to v0.4.2

actions/env.go, actions/env_test.go, actions/handlers.go, actions/handlers_test.go, actions/updateaction/issuecomment.go, actions/updateaction/pullrequest.go, actions/updateaction/pullrequest_test.go, actions/updateaction/release.go, actions/updateaction/release_test.go, actions/updateaction/repositorydispatch.go, go.mod, go.sum, repo/github.go, repo/pullrequest.go
Here is github.com/google/go-github/v33 v34.0.0, I hope it works.
=> Update github.com/google/go-github/v33 from v33.0.0 to v34.0.0

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.3, I hope it works.
=> Update golang from 1.16.2 to 1.16.3

actions/env.go, actions/env_test.go, actions/handlers.go, actions/handlers_test.go, actions/updateaction/issuecomment.go, actions/updateaction/pullrequest.go, actions/updateaction/pullrequest_test.go, actions/updateaction/release.go, actions/updateaction/release_test.go, actions/updateaction/repositorydispatch.go, go.mod, go.sum, repo/github.go, repo/pullrequest.go
Here is github.com/google/go-github/v34 v35.0.0, I hope it works.
=> Update github.com/google/go-github/v34 from v34.0.0 to v35.0.0

go.mod, go.sum
Here is github.com/google/go-github/v35 v35.1.0, I hope it works.
=> Update github.com/google/go-github/v35 from v35.0.0 to v35.1.0

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.4, I hope it works.
=> Update golang from 1.16.3 to 1.16.4

go.mod, go.sum
Here is github.com/google/go-github/v35 v35.2.0, I hope it works.
=> Update github.com/google/go-github/v35 from v35.1.0 to v35.2.0

go.mod, go.sum
Here is github.com/caarlos0/env/v6 v6.6.2, I hope it works.
=> Update github.com/caarlos0/env/v6 from v6.6.0 to v6.6.2

go.mod, go.sum
Here is github.com/go-git/go-git/v5 v5.4.2, I hope it works.
=> Update github.com/go-git/go-git/v5 from v5.4.1 to v5.4.2

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.5, I hope it works.
=> Update golang from 1.16.4 to 1.16.5

go.mod, go.sum
Here is github.com/google/go-github/v35 v35.3.0, I hope it works.
=> Update github.com/google/go-github/v35 from v35.2.0 to v35.3.0

actions/env.go, actions/env_test.go, actions/handlers.go, actions/handlers_test.go, actions/updateaction/issuecomment.go, actions/updateaction/pullrequest.go, actions/updateaction/pullrequest_test.go, actions/updateaction/release.go, actions/updateaction/release_test.go, actions/updateaction/repositorydispatch.go, go.mod, go.sum, repo/github.go, repo/pullrequest.go
Here is github.com/google/go-github/v35 v36.0.0, I hope it works.
=> Update github.com/google/go-github/v35 from v35.3.0 to v36.0.0

version/semver.go, version/semver_test.go
Promote some helpers from [action-update-docker](https://github.com/thepwagner/action-update-docker/blob/b149d63677ea19eb6c036464ef4417fbf59362c7/docker/check.go#L74-L97), because I'd like to use them in `action-update-docker-url`.
In particular, I noticed https://github.com/tianon/gosu/releases isn't being updated - these test support it.
=> semver helpers

actions/env.go, actions/env_test.go, actions/handlers.go, actions/handlers_test.go, actions/updateaction/issuecomment.go, actions/updateaction/pullrequest.go, actions/updateaction/pullrequest_test.go, actions/updateaction/release.go, actions/updateaction/release_test.go, actions/updateaction/repositorydispatch.go, go.mod, go.sum, repo/github.go, repo/pullrequest.go
Here is github.com/google/go-github/v36 v37.0.0, I hope it works.
=> Update github.com/google/go-github/v36 from v36.0.0 to v37.0.0

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.6, I hope it works.
=> Update golang from 1.16.5 to 1.16.6
